INSERT INTO public.tb_issues ("date",description,email_reporter,name_company,task,"time",url,manager) VALUES
	 ('2023-10-24','Falta de alternativas textuais para conteúdo visual, excluindo usuários com deficiência visual.','','Service now',0,'14:20:00','https://zup.service-now.com',NULL),
	 ('2023-10-27','Falta de rótulos adequados e identificação de campos em formulários, dificultando a entrada de dados para usuários de tecnologia assistiva.','','Zup net',0,'11:30:00','https://sites.google.com/zup.com.br/zup/home?authuser=0',NULL),
	 ('2023-10-02','Falta de estruturação correta do conteúdo, tornando a navegação e compreensão do site difícil para usuários de leitores de tela.','','Zscaler',0,'14:30:00','https://www.zscaler.com/',NULL),
	 ('2023-10-02','Phasellus non interdum libero. Pellentesque id erat vel ante accumsan gravida. Vivamus in volutpat justo. Suspendisse quis felis in libero viverra fermentum. Praesent ullamcorper urna et tortor malesuada, nec vehicula sapien posuere. Integer quis eros nec nulla lobortis aliquam.','','PulseWave Ltd.',3,'14:30:00','http://sub.example1.com/new-products/updates',NULL),
	 ('2023-10-07','In hac habitasse platea dictumst. Praesent vestibulum dapibus nibh. Etiam sollicitudin, ipsum eu pulvinar rutrum, tellus ipsum laoreet sapien, quis venenatis ante odio sit amet eros.','','Nebula Enterprises',3,'09:40:00','http://myfakeurl11.com/support/faq',NULL),
	 ('2023-10-19','Suspendisse vitae mauris ligula. Curabitur tristique dignissim justo, at ultricies justo facilisis nec.','','OmniTech Solutions',3,'10:15:00','http://example12.org/community/events/upcoming',NULL),
	 ('2023-10-22','Sed id ante. Donec ultrices, nisi nec vulputate vulputate, tellus urna vehicula ipsum, at consequat lectus metus quis justo.','','Cybex Corporation',3,'15:55:00','http://sub.example13.net/blog/featured-posts',NULL),
	 ('2023-10-25','Fusce metus lorem, vestibulum et ultrices nec, varius nec odio. Morbi cursus sapien in lectus volutpat, quis pulvinar urna tristique.','','QuantumPrime Enterprises',3,'08:25:00','http://testwebsite14.io/support/contact-us',NULL),
	 ('2023-10-28','Nunc eget augue. Nullam id dolor id nibh ultricies vehicula ut id elit.','','Synergy Co.',3,'12:00:00','http://mydomain15.com/gallery/recent-photos',NULL),
	 ('2023-10-21','Sed eu accumsan nibh. Etiam hendrerit, dolor vel vulputate bibendum, mauris odio tristique libero, vel hendrerit nisl velit non sem. Nulla ultrices, elit a congue sollicitudin, elit erat suscipit eros, vel vulputate elit mi et sapien. Sed finibus ultrices vestibulum.','','Innovix Corp.',3,'10:00:00','http://example7.org/faq/general/support',NULL);
INSERT INTO public.tb_issues ("date",description,email_reporter,name_company,task,"time",url,manager) VALUES
	 ('2023-10-30','Nulla facilisi. Sed lectus justo, viverra in sodales eget, congue ac tellus.','','Vertex Dynamics',3,'16:10:00','http://example10.io/careers/open-positions',NULL),
	 ('2023-10-11','Teste','manichi@gmail.com','.marcamaria',3,'15:41:32','https://seeufalarnaosaidireito.com',NULL),
	 ('2023-10-13','Vestibulum eu fringilla orci, nec tempus elit. Nullam sed cursus orci. Ut facilisis a elit nec cursus. Sed viverra, risus ut bibendum euismod, nulla felis viverra nisl, ac congue libero justo et sapien. Nam eget lacinia purus. Cras at massa urna.','','TechNova Enterprises',3,'12:40:00','http://subdomain2.example14.io/careers/apply-now',NULL),
	 ('2023-10-15','Falta de estrutura de títulos e subtítulos, dificultando a compreensão e navegação para usuários de leitores de tela.','','Stackspot',2,'09:00:00','https://stackspot.com/pt/home',NULL),
	 ('2023-10-13','Teste','','google',3,'14:11:58','http://google.com/shop',NULL),
	 ('2023-10-05','Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.','','TechNova Co.',3,'10:45:00','http://subdomain1.example2.com/services/pricing/contact',NULL),
	 ('2023-10-12','At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.','','Quantum Innovations',3,'11:10:00','http://test.example4.org/products/new',NULL),
	 ('2023-10-18','In ultrices ut ligula vel vehicula. Praesent nec turpis id leo hendrerit congue in non elit. Ut quis enim odio. Integer id risus sed erat convallis accumsan eu sit amet sapien. Nulla facilisi. Integer in cursus leo, vel blandit erat. Cras fringilla diam sit amet iaculis ultrices.','','NovaCorp',3,'13:45:00','http://mydomain6.com/features/how-it-works',NULL),
	 ('2023-10-18','Nam dictum risus ut tellus dignissim aliquet. Proin luctus sapien eget libero vehicula, in feugiat justo convallis. Suspendisse potenti. Vivamus vestibulum velit nec mauris vulputate, et malesuada sapien congue. Vestibulum efficitur quam eget est dictum, sit amet tincidunt eros congue.','','Synergy Solutions',3,'13:45:00','http://testsite6.com/faq/general/billing',NULL),
	 ('2023-10-24','Quisque facilisis vehicula leo, eget efficitur tortor malesuada sit amet. Fusce ultrices est ut orci facilisis ullamcorper. Nullam sit amet fermentum libero. Etiam cursus tortor vel efficitur finibus. Nulla a nisl a nisi cursus interdum. Vivamus hendrerit diam vel varius tincidunt.','','QuantumForge Ltd.',3,'14:20:00','http://mydomain8.com/press/media-kit',NULL);
INSERT INTO public.tb_issues ("date",description,email_reporter,name_company,task,"time",url,manager) VALUES
	 ('2023-10-21','Curabitur laoreet ut felis id malesuada. Sed iaculis gravida pharetra. Duis quis massa a tortor imperdiet lobortis nec nec justo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus rhoncus elementum malesuada. Ut scelerisque luctus quam, nec finibus risus congue id.','','Nebula TechCorp',3,'10:00:00','http://example7.org/blog/recent-articles',NULL),
	 ('2023-10-08','Falta de contraste adequado entre texto e plano de fundo, dificultando a leitura para pessoas com deficiência visual.','','Zupapp',1,'16:20:00','https://zup-pwa.dialog.cm/',NULL),
	 ('2023-10-07','Donec tincidunt a tellus quis cursus. Vivamus eu orci non libero consequat fringilla. Duis in bibendum erat. Sed condimentum lacus eu posuere venenatis. Sed accumsan tincidunt ligula ut posuere. Ut eget nisl arcu.','','QuantumSpark Solutions',3,'14:15:00','http://testwebsite12.org/feedback/customer-reviews',NULL),
	 ('2023-10-17','teste','','teste',3,'17:13:05','http://www.google.com/catalisa',NULL),
	 ('2023-10-13','teste','','google',3,'14:53:09','http://www.google.com',NULL),
	 ('2023-10-12',' Imagens não possuem descrição adequada para leitores de tela, violando a acessibilidade.','','App data',1,'11:10:00','https://cliente.apdata.com.br/zup/main.html',NULL),
	 ('2023-10-05','Integer eu odio nec odio iaculis vestibulum non nec sem. Quisque efficitur nec est at consequat. Morbi tristique nec arcu sit amet volutpat. Vivamus eget viverra purus. Integer ac enim non orci posuere bibendum.','','QuantumSolutions Co.',3,'10:45:00','http://fakeurl2.net/features/get-started/tutorials',NULL),
	 ('2023-10-11','Testando isso','faso@marcamaria.com','.marcamaria',3,'15:36:48','https://marcamaria.com',NULL),
	 ('2023-10-13','teste','','google',3,'10:57:29','http://www.google.com',NULL),
	 ('2023-10-08','Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.','','AeroTech Solutions',3,'16:20:00','http://fakewebsite3.net/about/team/locations',NULL);
INSERT INTO public.tb_issues ("date",description,email_reporter,name_company,task,"time",url,manager) VALUES
	 ('2023-10-13','teste','','google',3,'11:13:35','http://www.google.com/imagens',NULL),
	 ('2023-10-17','ju','','ju',3,'17:14:15','http://www.google.com/ju',NULL),
	 ('2023-10-17','thais','','thais',3,'17:15:59','http://www.google.com',NULL),
	 ('2023-10-30','Pellentesque ac quam nec justo efficitur bibendum. Nam nec arcu eu nisl viverra vestibulum id a purus. Duis auctor, metus nec volutpat blandit, felis arcu euismod dolor, ut vulputate elit ex a dolor. Vestibulum dapibus laoreet metus, ut cursus tortor consequat non. Praesent at ultrices orci.','','Stratify Innovations',3,'16:10:00','http://example10.io/about/our-mission/values',NULL),
	 ('2023-10-07','Donec tincidunt a tellus quis cursus. Vivamus eu orci non libero consequat fringilla. Duis in bibendum erat. Sed condimentum lacus eu posuere venenatis. Sed accumsan tincidunt ligula ut posuere. Ut euismod lectus vel dui fermentum, ut congue nulla vestibulum.','','QuantumSpark Solutions',3,'14:15:00','http://testwebsite12.org/feedback/customer-reviews',NULL),
	 ('2023-10-10','Curabitur congue dictum ligula, vel scelerisque metus elementum eu. Vestibulum in tincidunt lacus, quis tempor orci. Vivamus eu egestas purus. Suspendisse bibendum fringilla eros, id aliquet elit egestas a. Maecenas ullamcorper sagittis nisi, id tincidunt enim tincidunt a. Ut eget nisl arcu.','','DynaPrime Inc.',3,'10:35:00','http://example13.net/news/press-releases',NULL),
	 ('2023-10-13','Vestibulum eu fringilla orci, nec tempus elit. Nullam sed cursus orci. Ut facilisis a elit nec cursus. Sed viverra, risus ut bibendum euismod, nulla felis viverra nisl, ac congue libero justo et sapien. Nam eget lacinia purus. Cras at massa urna.','','TechNova Enterprises',3,'12:40:00','http://subdomain2.example14.io/careers/apply-now',NULL),
	 ('2023-10-16','Nam sed justo velit. Nullam elementum metus sed eros suscipit, et cursus justo tristique. Nunc euismod, velit vitae cursus convallis, velit urna malesuada ex, at ultrices tortor sapien vitae nisl. Morbi vitae nulla vel tortor auctor elementum. Ut sit amet massa quis turpis malesuada sollicitudin a id nisl.','','Synergy Co.',3,'15:25:00','http://myfakeurl15.com/support/submit-ticket',NULL),
	 ('2023-10-02','Phasellus non interdum libero. Pellentesque id erat vel ante accumsan gravida. Vivamus in volutpat justo. Suspendisse quis felis in libero viverra fermentum. Praesent ullamcorper urna et tortor malesuada, nec vehicula sapien posuere. Integer quis eros nec nulla lobortis aliquam.','','PulseWave Ltd.',3,'14:30:00','http://sub.example1.com/new-products/updates',NULL),
	 ('2023-10-12','Suspendisse auctor, dui in imperdiet viverra, metus purus viverra massa, ut vehicula augue sem in arcu. Nam tempor, nisl vitae interdum pharetra, nunc tortor luctus dui, a gravida erat velit at nulla. Nulla auctor non quam eget tincidunt. Proin et facilisis tortor. Ut congue ullamcorper sapien, id tincidunt tellus volutpat vitae.','','Zenith Innovations',3,'11:10:00','http://myfakeurl4.com/products/categories',NULL);
INSERT INTO public.tb_issues ("date",description,email_reporter,name_company,task,"time",url,manager) VALUES
	 ('2023-10-05','Integer eu odio nec odio iaculis vestibulum non nec sem. Quisque efficitur nec est at consequat. Morbi tristique nec arcu sit amet volutpat. Vivamus eget viverra purus. Integer ac enim non orci posuere bibendum.','','QuantumSolutions Co.',3,'10:45:00','http://fakeurl2.net/features/get-started/tutorials',NULL),
	 ('2023-10-21','Curabitur laoreet ut felis id malesuada. Sed iaculis gravida pharetra. Duis quis massa a tortor imperdiet lobortis nec nec justo. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus rhoncus elementum malesuada. Ut scelerisque luctus quam, nec finibus risus congue id.','','Nebula TechCorp',3,'10:00:00','http://example7.org/blog/recent-articles',NULL),
	 ('2023-10-15','Falta de foco adequado nos elementos interativos, dificultando a navegação para usuários de tecnologia assistiva.','','Zenity',2,'09:00:00','https://people.zup.com.br/',NULL),
	 ('2023-10-24','Quisque facilisis vehicula leo, eget efficitur tortor malesuada sit amet. Fusce ultrices est ut orci facilisis ullamcorper. Nullam sit amet fermentum libero. Etiam cursus tortor vel efficitur finibus. Nulla a nisl a nisi cursus interdum. Vivamus hendrerit diam vel varius tincidunt.','','QuantumForge Ltd.',3,'14:20:00','http://mydomain8.com/press/media-kit',NULL),
	 ('2023-10-18','Nam dictum risus ut tellus dignissim aliquet. Proin luctus sapien eget libero vehicula, in feugiat justo convallis. Suspendisse potenti. Vivamus vestibulum velit nec mauris vulputate, et malesuada sapien congue. Vestibulum efficitur quam eget est dictum, sit amet tincidunt eros congue.','','Synergy Solutions',3,'13:45:00','http://testsite6.com/faq/general/billing',NULL),
	 ('2023-10-27','Sed commodo, orci et imperdiet tristique, libero velit facilisis est, nec imperdiet odio urna vitae nulla. Nunc ac purus tristique, tincidunt metus vel, tempus velit. Fusce in libero in dolor posuere aliquet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.','','DynaTech Corp.',3,'11:30:00','http://fakeexample9.net/community/forum/general-discussions',NULL),
	 ('2023-10-08','Pellentesque a tincidunt quam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed euismod dolor quis sapien ultrices, ac aliquam tortor luctus. In hac habitasse platea dictumst. Vestibulum et tristique metus, in suscipit dui. Fusce vel tincidunt elit.','','Stratify Inc.',3,'16:20:00','http://examplewebsite3.org/about/history/our-team',NULL),
	 ('2023-10-04','Vestibulum fringilla purus at bibendum hendrerit. Maecenas quis consequat nibh. Etiam at metus ac nibh auctor dictum. Nam id erat non urna varius tincidunt. Vivamus lobortis tincidunt justo non vulputate. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae.','','Nova Enterprises',3,'09:45:00','http://sub.example11.com/gallery/photos',NULL),
	 ('2023-10-10','Curabitur congue dictum ligula, vel scelerisque metus elementum eu. Vestibulum in tincidunt lacus, quis tempor orci. Vivamus eu egestas purus. Suspendisse bibendum fringilla eros, id aliquet elit egestas a. Maecenas ullamcorper sagittis nisi, id tincidunt enim tincidunt a. Ut eget nisl arcu.','','DynaPrime Inc.',3,'10:35:00','http://example13.net/news/press-releases',NULL),
	 ('2023-10-27','Sed commodo, orci et imperdiet tristique, libero velit facilisis est, nec imperdiet odio urna vitae nulla. Nunc ac purus tristique, tincidunt metus vel, tempus velit. Fusce in libero in dolor posuere aliquet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames.','','DynaTech Corp.',3,'11:30:00','http://fakeexample9.net/community/forum/general-discussions',NULL);
INSERT INTO public.tb_issues ("date",description,email_reporter,name_company,task,"time",url,manager) VALUES
	 ('2023-10-30','Pellentesque ac quam nec justo efficitur bibendum. Nam nec arcu eu nisl viverra vestibulum id a purus. Duis auctor, metus nec volutpat blandit, felis arcu euismod dolor, ut vulputate elit ex a dolor. Vestibulum dapibus laoreet metus, ut cursus tortor consequat non. Praesent at ultrices orci.','','Stratify Innovations',3,'16:10:00','http://example10.io/about/our-mission/values',NULL),
	 ('2023-10-04','Vestibulum fringilla purus at bibendum hendrerit. Maecenas quis consequat nibh. Etiam at metus ac nibh auctor dictum. Nam id erat non urna varius tincidunt. Vivamus lobortis tincidunt justo non vulputate. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae.','','Nova Enterprises',3,'09:45:00','http://sub.example11.com/gallery/photos',NULL),
	 ('2023-10-15','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin euismod odio ut ante consectetur vestibulum. Sed ut bibendum metus, vel luctus sapien. Vivamus dictum neque in arcu scelerisque, ut consequat ex tincidunt. Sed ac justo ut massa laoreet tincidunt in at justo. Vivamus ac erat a est ultr','','ByteWave Ltd.',3,'09:00:00','http://sub.example5.io/blog/articles',NULL),
	 ('2023-10-16','Nam sed justo velit. Nullam elementum metus sed eros suscipit, et cursus justo tristique. Nunc euismod, velit vitae cursus convallis, velit urna malesuada ex, at ultrices tortor sapien vitae nisl. Morbi vitae nulla vel tortor auctor elementum. Ut sit amet massa quis turpis malesuada sollicitudin a id nisl.','','Synergy Co.',3,'15:25:00','http://myfakeurl15.com/support/submit-ticket',NULL),
	 ('2023-10-19','teste','','teste do submit',3,'09:39:23','http://www.google.com',NULL),
	 ('2023-10-19','teste','','terra',3,'09:41:51','http://www.terra.com.br',NULL),
	 ('2023-10-19','Encontrei um erro: o catalisa não tem site!','','Catalisa',3,'10:40:44','http://www.zup.com.br/catalisa',NULL);
